# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fcps_css',
                'doc_host': 'https://samiit.github.io',
                'git_url': 'https://github.com/samiit/fcps_css',
                'lib_path': 'fcps_css'},
  'syms': {'fcps_css.core': {'fcps_css.core.foo': ('core.html#foo', 'fcps_css/core.py')}}}
